Section "InputClass"
	Identifier "touchscreen catchall"
	MatchIsTouchscreen "on"
	Driver "evtouch"
    Option "MinY" "430"
    Option "MinX" "368"
    Option "MaxX" "1647"
    Option "MaxY" "1647"
EndSection
