#!/bin/sh
#
# inputattach initscript
#
### BEGIN INIT INFO
# Provides:          inputattach
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Store and restore joystick calibration
# Description:       This script restores joystick calibration on
#                    shutdown and restores it on bootup.
### END INIT INFO

# Don't use set -e; check exit status instead

# Exit silently if package is no longer installed
[ -x /usr/bin/inputattach ] || exit 0

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Restoring inputattach"
	start-stop-daemon --background --pidfile /var/run/inputattach.pid  --make-pidfile --exec /usr/bin/inputattach --start -- --dualnot /dev/ttyS4
	log_end_msg 0
	exit 0
	;;
  stop)
	log_daemon_msg "Storing joystick calibration"
	start-stop-daemon --stop --pidfile /var/run/inputattach.pid
	exit 0
	;;
  restart|force-reload)
	EXITSTATUS=0
	$0 stop || EXITSTATUS=1
	$0 start || EXITSTATUS=1
	exit $EXITSTATUS
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 3
	;;
esac

