#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# Should you need to contact me, the author, you can do so either by
# e-mail - mail your message to <vojtech@ucw.cz>, or by paper mail:
# Vojtech Pavlik, Simunkova 1594, Prague 8, 182 00 Czech Republic
#
#
# Edit the options below to suit your needs
#

CC		= gcc
CFLAGS		= -g -O2 -Wall -I../linux/include

PROGRAMS	= inputattach

compile: $(PROGRAMS)

clean:
	$(RM) *.o *.swp $(PROGRAMS) *.orig *.rej map *~

